cc_library(
    name = "strategy",
    hdrs = ["strategy.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//cpp/interfaces:execution_model",
        "//cpp/orderbook",
    ],
)

cc_library(
    name = "position_tracker",
    srcs = ["postion_tracker.cpp"],
    hdrs = ["position_tracker.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//cpp/interfaces:execution_model",
        "//cpp/orderbook",
    ],
)

cc_library(
    name = "results",
    hdrs = ["results.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//cpp/orderbook",
    ],
)

cc_library(
    name = "simple_strategy",
    hdrs = ["simple_strategy.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":strategy",
        "//cpp/interfaces:execution_model",
    ],
)

cc_library(
    name = "backtester",
    srcs = ["backtester.cpp"],
    hdrs = ["backtester.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":strategy",
        ":results",
        ":position_tracker",
        "//cpp/trades:data_manager",
        "//cpp/market:trade_only_market_view",
        "//cpp/execution:execution",
    ],
)

cc_test(
    name = "position_tracker_test",
    srcs = ["position_tracker_test.cpp"],
    deps = [
        ":position_tracker",
        "@googletest//:gtest_main",
    ],
)

cc_binary(
    name = "backtester_example",
    srcs = ["backtester_example.cpp"],
    deps = [
        ":backtester",
        ":simple_strategy",
    ],
)
